config/routes.rb
Rails.application.routes.draw do
  root 'urls#new'
  resources :urls, only: [:new, :create, :show]
  get '/urls/:short_url', to: 'urls#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
    SHORT_URL_LENGTH = 6
    # LONG_URL_VALIDATION_FORMAT = /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#?&\/\/=]*)?\z/

    validates :long_url, presence: true, on: :create
    # validates :long_url, format: {with: LONG_URL_VALIDATION_FORMAT}
    before_create :generate_short_url

    def generate_short_url
        url = ([*("a".."z"),*("0".."9")]).sample(SHORT_URL_LENGTH).join
        old_url = Url.where(short_url: url).last
        if old_url.present?
            self.generate_short_url
        else
            self.short_url = url
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show ]

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # POST /urls or /urls.json
  def create

    shortened_url = Url.find_by_short_url(url_params[:long_url])
    if shortened_url
      redirect_to shortened_url.long_url
    else
      existing_url = Url.find_by_long_url(url_params[:long_url])
      if existing_url
        respond_to do |format|
          format.html { redirect_to existing_url, notice: "This url has already been shortened." }
          format.json { render :show, status: :found, location: existing_url }
        end
      else
        @url = Url.new(url_params)
        respond_to do |format|
          if @url.save
            format.html { redirect_to @url, notice: "Url was successfully shortened." }
            format.json { render :show, status: :created, location: @url }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @url.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:long_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenUrl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :long_url %>
  </div>

  <div class="actions">
    <%= form.submit "Shorten URL / Get original URL" %>
  </div>
<% end %>

app/views/urls/new.html.erb
<h1>Shorten URL / Get original URL</h1>

<%= render 'form', url: @url %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Long url:</strong>
  <%= link_to @url.long_url, @url.long_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @url.short_url %>
</p>

<%= link_to 'Look for another URL', new_url_path %>